version: "3.8"

services:
  frontend:
    build: .
    container_name: vue-develop
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true