version: "3.8"

services:
  frontend:
    build: .
    container_name: vue-develop
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./test:/app
      - /app/node_modules
    command: sh -c "npm install && npm run serve -- --host 0.0.0.0"
